TRUNCATE TABLE accounts CASCADE;
INSERT INTO accounts (code, name, type) VALUES
('1011', 'Capital subscris nevărsat', 'pasiv'),
('1012', 'Capital subscris vărsat', 'pasiv'),
('1015', 'Patrimoniul regiei', 'pasiv'),
('1016', 'Patrimoniul public', 'pasiv'),
('1017', 'Patrimoniul privat', 'pasiv'),
('1018', 'Patrimoniul institutelor naționale de cercetare-dezvoltare', 'pasiv'),
('1031', 'Beneficii acordate angajaților sub forma instrumentelor de capitaluri proprii', 'pasiv'),
('1033', 'Diferențe de curs valutar în relație cu investiția netă într-o entitate străină', 'bifunctional'),
('1038', 'Diferențe din modificarea valorii juste a activelor financiare disponibile în vederea vânzării', 'bifunctional'),
('1041', 'Prime de emisiune', 'pasiv'),
('1042', 'Prime de fuziune/divizare', 'pasiv'),
('1043', 'Prime de aport', 'pasiv'),
('1044', 'Prime de conversie a obligațiunilor în acțiuni', 'pasiv'),
('105', 'Rezerve din reevaluare', 'pasiv'),
('1061', 'Rezerve legale', 'pasiv'),
('1063', 'Rezerve statutare sau contractuale', 'pasiv'),
('1068', 'Alte rezerve', 'pasiv'),
('107', 'Diferențe de curs valutar din conversie', 'bifunctional'),
('1081', 'Interese care nu controlează - rezultatul exercițiului financiar', 'bifunctional'),
('1082', 'Interese care nu controlează - alte capitaluri proprii', 'bifunctional'),
('1091', 'Acțiuni proprii deținute pe termen scurt', 'activ'),
('1092', 'Acțiuni proprii deținute pe termen lung', 'activ'),
('1095', 'Acțiuni proprii reprezentând titluri deținute de societatea absorbită la societatea absorbantă', 'activ'),
('1171', 'Rezultatul reportat reprezentând profitul nerepartizat sau pierderea neacoperită', 'bifunctional'),
('1172', 'Rezultatul reportat provenit din adoptarea pentru prima dată a IAS, mai puțin IAS 29', 'bifunctional'),
('1173', 'Rezultatul reportat provenit din modificările politicilor contabile', 'bifunctional'),
('1174', 'Rezultatul reportat provenit din corectarea erorilor contabile', 'bifunctional'),
('1175', 'Rezultatul reportat reprezentând surplusul realizat din rezerve din reevaluare', 'pasiv'),
('1176', 'Rezultatul reportat provenit din trecerea la aplicarea reglementărilor contabile conforme cu directivele europene', 'bifunctional'),
('121', 'Profit sau pierdere', 'bifunctional'),
('129', 'Repartizarea profitului', 'activ'),
('1411', 'Câștiguri legate de vânzarea instrumentelor de capitaluri proprii', 'pasiv'),
('1412', 'Câștiguri legate de anularea instrumentelor de capitaluri proprii', 'pasiv'),
('1491', 'Pierderi rezultate din vânzarea instrumentelor de capitaluri proprii', 'activ'),
('1495', 'Pierderi rezultate din reorganizări, care sunt determinate de anularea titlurilor deținute', 'activ'),
('1496', 'Pierderi rezultate din reorganizări de societăți, corespunzătoare activului net negativ al societății absorbite', 'activ'),
('1498', 'Alte pierderi legate de instrumentele de capitaluri proprii', 'activ'),
('1511', 'Provizioane pentru litigii', 'pasiv'),
('1512', 'Provizioane pentru garanții acordate clienților', 'pasiv'),
('1513', 'Provizioane pentru dezafectare imobilizări corporale și alte acțiuni similare', 'pasiv'),
('1514', 'Provizioane pentru restructurare', 'pasiv'),
('1515', 'Provizioane pentru pensii și obligații similare', 'pasiv'),
('1516', 'Provizioane pentru impozite', 'pasiv'),
('1517', 'Provizioane pentru terminarea contractului de muncă', 'pasiv'),
('1518', 'Alte provizioane', 'pasiv'),
('1614', 'Împrumuturi externe din emisiuni de obligațiuni garantate de stat', 'pasiv'),
('1615', 'Împrumuturi externe din emisiuni de obligațiuni garantate de bănci', 'pasiv'),
('1617', 'Împrumuturi interne din emisiuni de obligațiuni garantate de stat', 'pasiv'),
('1618', 'Alte împrumuturi din emisiuni de obligațiuni', 'pasiv'),
('1621', 'Credite bancare pe termen lung', 'pasiv'),
('1622', 'Credite bancare pe termen lung nerambursate la scadență', 'pasiv'),
('1623', 'Credite externe guvernamentale', 'pasiv'),
('1624', 'Credite bancare externe garantate de stat', 'pasiv'),
('1625', 'Credite bancare externe garantate de bănci', 'pasiv'),
('1626', 'Credite de la trezoreria statului', 'pasiv'),
('1627', 'Credite bancare interne garantate de stat', 'pasiv'),
('1661', 'Datorii față de entitățile afiliate', 'pasiv'),
('1663', 'Datorii față de entitățile asociate și entitățile controlate în comun', 'pasiv'),
('167', 'Alte împrumuturi și datorii asimilate', 'pasiv'),
('1681', 'Dobânzi aferente împrumuturilor din emisiuni de obligațiuni', 'pasiv'),
('1682', 'Dobânzi aferente creditelor bancare pe termen lung', 'pasiv'),
('1685', 'Dobânzi aferente datoriilor față de entitățile afiliate', 'pasiv'),
('1686', 'Dobânzi aferente datoriilor față de entitățile asociate', 'pasiv'),
('1687', 'Dobânzi aferente altor împrumuturi și datorii asimilate', 'pasiv'),
('1691', 'Prime privind rambursarea obligațiunilor', 'activ'),
('1692', 'Prime privind rambursarea altor datorii', 'activ'),
('201', 'Cheltuieli de constituire', 'activ'),
('203', 'Cheltuieli de dezvoltare', 'activ'),
('205', 'Concesiuni, brevete, licențe, mărci comerciale, drepturi și active similare', 'activ'),
('206', 'Active necorporale de explorare și evaluare a resurselor minerale', 'activ'),
('2071', 'Fond comercial pozitiv', 'activ'),
('2075', 'Fond comercial negativ', 'pasiv'),
('208', 'Alte imobilizări necorporale', 'activ'),
('2111', 'Terenuri', 'activ'),
('2112', 'Amenajări de terenuri', 'activ'),
('212', 'Construcții', 'activ'),
('2131', 'Echipamente tehnologice (mașini, utilaje și instalații de lucru)', 'activ'),
('2132', 'Aparate și instalații de măsurare, control și reglare', 'activ'),
('2133', 'Mijloace de transport', 'activ'),
('214', 'Mobilier, aparatură birotică, echipamente de protecție', 'activ'),
('215', 'Investiții imobiliare', 'activ'),
('216', 'Active corporale de explorare și evaluare a resurselor minerale', 'activ'),
('217', 'Active biologice productive', 'activ'),
('223', 'Instalații tehnice și mijloace de transport în curs de aprovizionare', 'activ'),
('224', 'Mobilier și aparatură birotică în curs de aprovizionare', 'activ'),
('227', 'Active biologice productive în curs de aprovizionare', 'activ'),
('231', 'Imobilizări corporale în curs de execuție', 'activ'),
('235', 'Investiții imobiliare în curs de execuție', 'activ'),
('261', 'Acțiuni deținute la entitățile afiliate', 'activ'),
('262', 'Acțiuni deținute la entități asociate', 'activ'),
('263', 'Acțiuni deținute la entități controlate în comun', 'activ'),
('264', 'Titluri puse în echivalență', 'activ'),
('265', 'Alte titluri imobilizate', 'activ'),
('266', 'Certificate verzi amânate', 'activ'),
('2671', 'Sume de încasat de la entitățile afiliate', 'activ'),
('2672', 'Dobânda aferentă sumelor de încasat de la entitățile afiliate', 'activ'),
('2673', 'Creanțe față de entitățile asociate și entitățile controlate în comun', 'activ'),
('2674', 'Dobânda aferentă creanțelor față de entitățile asociate', 'activ'),
('2675', 'Împrumuturi acordate pe termen lung', 'activ'),
('2676', 'Dobânda aferentă împrumuturilor acordate pe termen lung', 'activ'),
('2677', 'Obligațiuni achiziționate cu ocazia emisiunilor efectuate de terți', 'activ'),
('2678', 'Alte creanțe imobilizate', 'activ'),
('2679', 'Dobânzi aferente altor creanțe imobilizate', 'activ'),
('2691', 'Vărsăminte de efectuat privind acțiunile deținute la entitățile afiliate', 'pasiv'),
('2692', 'Vărsăminte de efectuat privind acțiunile deținute la entități asociate', 'pasiv'),
('2693', 'Vărsăminte de efectuat privind acțiunile deținute la entități controlate în comun', 'pasiv'),
('2695', 'Vărsăminte de efectuat pentru alte imobilizări financiare', 'pasiv'),
('2801', 'Amortizarea cheltuielilor de constituire', 'pasiv'),
('2803', 'Amortizarea cheltuielilor de dezvoltare', 'pasiv'),
('2805', 'Amortizarea concesiunilor, brevetelor, licențelor, mărcilor comerciale', 'pasiv'),
('2806', 'Amortizarea activelor necorporale de explorare și evaluare a resurselor minerale', 'pasiv'),
('2807', 'Amortizarea fondului comercial', 'pasiv'),
('2808', 'Amortizarea altor imobilizări necorporale', 'pasiv'),
('2811', 'Amortizarea amenajărilor de terenuri', 'pasiv'),
('2812', 'Amortizarea construcțiilor', 'pasiv'),
('2813', 'Amortizarea instalațiilor și mijloacelor de transport', 'pasiv'),
('2814', 'Amortizarea altor imobilizări corporale', 'pasiv'),
('2815', 'Amortizarea investițiilor imobiliare', 'pasiv'),
('2816', 'Amortizarea activelor corporale de explorare și evaluare a resurselor minerale', 'pasiv'),
('2817', 'Amortizarea activelor biologice productive', 'pasiv'),
('2903', 'Ajustări pentru deprecierea cheltuielilor de dezvoltare', 'pasiv'),
('2905', 'Ajustări pentru deprecierea concesiunilor, brevetelor, licențelor', 'pasiv'),
('2906', 'Ajustări pentru deprecierea activelor necorporale de explorare și evaluare', 'pasiv'),
('2908', 'Ajustări pentru deprecierea altor imobilizări necorporale', 'pasiv'),
('2911', 'Ajustări pentru deprecierea terenurilor și amenajărilor de terenuri', 'pasiv'),
('2912', 'Ajustări pentru deprecierea construcțiilor', 'pasiv'),
('2913', 'Ajustări pentru deprecierea instalațiilor și mijloacelor de transport', 'pasiv'),
('2914', 'Ajustări pentru deprecierea altor imobilizări corporale', 'pasiv'),
('2915', 'Ajustări pentru deprecierea investițiilor imobiliare', 'pasiv'),
('2916', 'Ajustări pentru deprecierea activelor corporale de explorare și evaluare', 'pasiv'),
('2917', 'Ajustări pentru deprecierea activelor biologice productive', 'pasiv'),
('2931', 'Ajustări pentru deprecierea imobilizărilor corporale în curs de execuție', 'pasiv'),
('2935', 'Ajustări pentru deprecierea investițiilor imobiliare în curs de execuție', 'pasiv'),
('2961', 'Ajustări pentru pierderea de valoare a acțiunilor deținute la entitățile afiliate', 'pasiv'),
('2962', 'Ajustări pentru pierderea de valoare a acțiunilor deținute la entități asociate', 'pasiv'),
('2963', 'Ajustări pentru pierderea de valoare a altor titluri imobilizate', 'pasiv'),
('2964', 'Ajustări pentru pierderea de valoare a sumelor de încasat de la entitățile afiliate', 'pasiv'),
('2965', 'Ajustări pentru pierderea de valoare a creanțelor față de entitățile asociate', 'pasiv'),
('2966', 'Ajustări pentru pierderea de valoare a împrumuturilor acordate pe termen lung', 'pasiv'),
('2968', 'Ajustări pentru pierderea de valoare a altor creanțe imobilizate', 'pasiv'),
('301', 'Materii prime', 'activ'),
('3021', 'Materiale auxiliare', 'activ'),
('3022', 'Combustibili', 'activ'),
('3023', 'Materiale pentru ambalat', 'activ'),
('3024', 'Piese de schimb', 'activ'),
('3025', 'Semințe și materiale de plantat', 'activ'),
('3026', 'Furaje', 'activ'),
('3028', 'Alte materiale consumabile', 'activ'),
('303', 'Materiale de natura obiectelor de inventar', 'activ'),
('308', 'Diferențe de preț la materii prime și materiale', 'bifunctional'),
('321', 'Materii prime în curs de aprovizionare', 'activ'),
('322', 'Materiale consumabile în curs de aprovizionare', 'activ'),
('323', 'Materiale de natura obiectelor de inventar în curs de aprovizionare', 'activ'),
('326', 'Active biologice de natura stocurilor în curs de aprovizionare', 'activ'),
('327', 'Mărfuri în curs de aprovizionare', 'activ'),
('328', 'Ambalaje în curs de aprovizionare', 'activ'),
('331', 'Produse în curs de execuție', 'activ'),
('332', 'Servicii în curs de execuție', 'activ'),
('341', 'Semifabricate', 'activ'),
('345', 'Produse finite', 'activ'),
('346', 'Produse reziduale', 'activ'),
('347', 'Produse agricole', 'activ'),
('348', 'Diferențe de preț la produse', 'bifunctional'),
('351', 'Materii și materiale aflate la terți', 'activ'),
('354', 'Produse aflate la terți', 'activ'),
('356', 'Active biologice de natura stocurilor aflate la terți', 'activ'),
('357', 'Mărfuri aflate la terți', 'activ'),
('358', 'Ambalaje aflate la terți', 'activ'),
('361', 'Active biologice de natura stocurilor', 'activ'),
('368', 'Diferențe de preț la active biologice de natura stocurilor', 'bifunctional'),
('371', 'Mărfuri', 'activ'),
('378', 'Diferențe de preț la mărfuri', 'bifunctional'),
('381', 'Ambalaje', 'activ'),
('388', 'Diferențe de preț la ambalaje', 'bifunctional'),
('391', 'Ajustări pentru deprecierea materiilor prime', 'pasiv'),
('3921', 'Ajustări pentru deprecierea materialelor consumabile', 'pasiv'),
('3922', 'Ajustări pentru deprecierea materialelor de natura obiectelor de inventar', 'pasiv'),
('393', 'Ajustări pentru deprecierea producției în curs de execuție', 'pasiv'),
('3941', 'Ajustări pentru deprecierea semifabricatelor', 'pasiv'),
('3945', 'Ajustări pentru deprecierea produselor finite', 'pasiv'),
('3946', 'Ajustări pentru deprecierea produselor reziduale', 'pasiv'),
('3947', 'Ajustări pentru deprecierea produselor agricole', 'pasiv'),
('3951', 'Ajustări pentru deprecierea materiilor și materialelor aflate la terți', 'pasiv'),
('3952', 'Ajustări pentru deprecierea semifabricatelor aflate la terți', 'pasiv'),
('3953', 'Ajustări pentru deprecierea produselor finite aflate la terți', 'pasiv'),
('3954', 'Ajustări pentru deprecierea produselor reziduale aflate la terți', 'pasiv'),
('3955', 'Ajustări pentru deprecierea produselor agricole aflate la terți', 'pasiv'),
('3956', 'Ajustări pentru deprecierea activelor biologice de natura stocurilor aflate la terți', 'pasiv'),
('3957', 'Ajustări pentru deprecierea mărfurilor aflate la terți', 'pasiv'),
('3958', 'Ajustări pentru deprecierea ambalajelor aflate la terți', 'pasiv'),
('396', 'Ajustări pentru deprecierea activelor biologice de natura stocurilor', 'pasiv'),
('397', 'Ajustări pentru deprecierea mărfurilor', 'pasiv'),
('398', 'Ajustări pentru deprecierea ambalajelor', 'pasiv'),
('401', 'Furnizori', 'pasiv'),
('403', 'Efecte de plătit', 'pasiv'),
('404', 'Furnizori de imobilizări', 'pasiv'),
('405', 'Efecte de plătit pentru imobilizări', 'pasiv'),
('408', 'Furnizori - facturi nesosite', 'pasiv'),
('4091', 'Furnizori - debitori pentru cumpărări de bunuri de natura stocurilor', 'activ'),
('4092', 'Furnizori - debitori pentru prestări de servicii', 'activ'),
('4093', 'Avansuri acordate pentru imobilizări corporale', 'activ'),
('4094', 'Avansuri acordate pentru imobilizări necorporale', 'activ'),
('4111', 'Clienți', 'activ'),
('4118', 'Clienți incerți sau în litigiu', 'activ'),
('413', 'Efecte de primit de la clienți', 'activ'),
('418', 'Clienți - facturi de întocmit', 'activ'),
('419', 'Clienți - creditori', 'pasiv'),
('421', 'Personal - salarii datorate', 'pasiv'),
('423', 'Personal - ajutoare materiale datorate', 'pasiv'),
('424', 'Prime reprezentând participarea personalului la profit', 'pasiv'),
('425', 'Avansuri acordate personalului', 'activ'),
('426', 'Drepturi de personal neridicate', 'pasiv'),
('427', 'Rețineri din salarii datorate terților', 'pasiv'),
('4281', 'Alte datorii în legătură cu personalul', 'pasiv'),
('4282', 'Alte creanțe în legătură cu personalul', 'activ'),
('4311', 'Contribuția unității la asigurările sociale', 'pasiv'),
('4312', 'Contribuția personalului la asigurările sociale', 'pasiv'),
('4313', 'Contribuția angajatorului pentru asigurările sociale de sănătate', 'pasiv'),
('4314', 'Contribuția angajaților pentru asigurările sociale de sănătate', 'pasiv'),
('4315', 'Contribuția de asigurări sociale (CAS)', 'pasiv'),
('4316', 'Contribuția de asigurări sociale de sănătate (CASS)', 'pasiv'),
('4318', 'Alte contribuții pentru asigurările sociale de sănătate', 'pasiv'),
('436', 'Contribuția asiguratorie pentru muncă (CAM)', 'pasiv'),
('4371', 'Contribuția unității la fondul de șomaj', 'pasiv'),
('4372', 'Contribuția personalului la fondul de șomaj', 'pasiv'),
('4381', 'Alte datorii sociale', 'pasiv'),
('4382', 'Alte creanțe sociale', 'activ'),
('4411', 'Impozitul pe profit', 'pasiv'),
('4415', 'Impozitul specific unor activități', 'pasiv'),
('4417', 'Impozitul pe profit la nivelul impozitului minim pe cifra de afaceri', 'pasiv'),
('4418', 'Impozitul pe venit', 'pasiv'),
('4423', 'TVA de plată', 'pasiv'),
('4424', 'TVA de recuperat', 'activ'),
('4426', 'TVA deductibilă', 'activ'),
('4427', 'TVA colectată', 'pasiv'),
('4428', 'TVA neexigibilă', 'bifunctional'),
('444', 'Impozitul pe venituri de natura salariilor', 'pasiv'),
('4451', 'Subvenții guvernamentale', 'activ'),
('4452', 'Împrumuturi nerambursabile cu caracter de subvenții', 'activ'),
('4458', 'Alte sume primite cu caracter de subvenții', 'activ'),
('446', 'Alte impozite, taxe și vărsăminte asimilate', 'pasiv'),
('447', 'Fonduri speciale - taxe și vărsăminte asimilate', 'pasiv'),
('4481', 'Alte datorii față de bugetul statului', 'pasiv'),
('4482', 'Alte creanțe privind bugetul statului', 'activ'),
('4511', 'Decontări între entitățile afiliate', 'bifunctional'),
('4518', 'Dobânzi aferente decontărilor între entitățile afiliate', 'bifunctional'),
('4531', 'Decontări cu entitățile asociate și entitățile controlate în comun', 'bifunctional'),
('4538', 'Dobânzi aferente decontărilor cu entitățile asociate', 'bifunctional'),
('4551', 'Acționari/asociați - conturi curente', 'pasiv'),
('4558', 'Acționari/asociați - dobânzi la conturi curente', 'pasiv'),
('456', 'Decontări cu acționarii/asociații privind capitalul', 'bifunctional'),
('457', 'Dividende de plată', 'pasiv'),
('4581', 'Decontări din operațiuni în participație - pasiv', 'pasiv'),
('4582', 'Decontări din operațiuni în participație - activ', 'activ'),
('461', 'Debitori diverși', 'activ'),
('462', 'Creditori diverși', 'pasiv'),
('463', 'Creanțe reprezentând dividende repartizate în cursul exercițiului financiar', 'activ'),
('4661', 'Datorii din operațiuni de fiducie', 'pasiv'),
('4662', 'Creanțe din operațiuni de fiducie', 'activ'),
('467', 'Datorii aferente distribuirilor interimare de dividende', 'pasiv'),
('471', 'Cheltuieli înregistrate în avans', 'activ'),
('472', 'Venituri înregistrate în avans', 'pasiv'),
('473', 'Decontări din operațiuni în curs de clarificare', 'bifunctional'),
('4751', 'Subvenții guvernamentale pentru investiții', 'pasiv'),
('4752', 'Împrumuturi nerambursabile cu caracter de subvenții pentru investiții', 'pasiv'),
('4753', 'Donații pentru investiții', 'pasiv'),
('4754', 'Plusuri de inventar de natura imobilizărilor', 'pasiv'),
('4758', 'Alte sume primite cu caracter de subvenții pentru investiții', 'pasiv'),
('478', 'Venituri în avans aferente activelor primite prin transfer de la clienți', 'pasiv'),
('481', 'Decontări între unitate și subunități', 'bifunctional'),
('482', 'Decontări între subunități', 'bifunctional'),
('4901', 'Ajustări pentru deprecierea creanțelor aferente cumpărărilor de bunuri', 'pasiv'),
('4902', 'Ajustări pentru deprecierea creanțelor aferente prestărilor de servicii', 'pasiv'),
('4903', 'Ajustări pentru deprecierea creanțelor aferente imobilizărilor corporale', 'pasiv'),
('4904', 'Ajustări pentru deprecierea creanțelor aferente imobilizărilor necorporale', 'pasiv'),
('491', 'Ajustări pentru deprecierea creanțelor - clienți', 'pasiv'),
('495', 'Ajustări pentru deprecierea creanțelor - decontări în cadrul grupului', 'pasiv'),
('496', 'Ajustări pentru deprecierea creanțelor - debitori diverși', 'pasiv'),
('501', 'Acțiuni deținute la entitățile afiliate', 'activ'),
('505', 'Obligațiuni emise și răscumpărate', 'activ'),
('506', 'Obligațiuni', 'activ'),
('507', 'Certificate verzi primite', 'activ'),
('5081', 'Alte titluri de plasament', 'activ'),
('5088', 'Dobânzi la obligațiuni și titluri de plasament', 'activ'),
('5091', 'Vărsăminte de efectuat pentru acțiunile deținute la entitățile afiliate', 'pasiv'),
('5092', 'Vărsăminte de efectuat pentru alte investiții pe termen scurt', 'pasiv'),
('5112', 'Cecuri de încasat', 'activ'),
('5113', 'Efecte de încasat', 'activ'),
('5114', 'Efecte remise spre scontare', 'activ'),
('5121', 'Conturi la bănci în lei', 'activ'),
('5124', 'Conturi la bănci în valută', 'activ'),
('5125', 'Sume în curs de decontare', 'activ'),
('5186', 'Dobânzi de plătit', 'pasiv'),
('5187', 'Dobânzi de încasat', 'activ'),
('5191', 'Credite bancare pe termen scurt', 'pasiv'),
('5192', 'Credite bancare pe termen scurt nerambursate la scadență', 'pasiv'),
('5193', 'Credite externe guvernamentale', 'pasiv'),
('5194', 'Credite externe garantate de stat', 'pasiv'),
('5195', 'Credite externe garantate de bănci', 'pasiv'),
('5196', 'Credite de la Trezoreria Statului', 'pasiv'),
('5197', 'Credite interne garantate de stat', 'pasiv'),
('5198', 'Dobânzi aferente creditelor bancare pe termen scurt', 'pasiv'),
('5311', 'Casa în lei', 'activ'),
('5314', 'Casa în valută', 'activ'),
('5321', 'Timbre fiscale și poștale', 'activ'),
('5322', 'Bilete de tratament și odihnă', 'activ'),
('5323', 'Tichete și bilete de călătorie', 'activ'),
('5328', 'Alte valori', 'activ'),
('5411', 'Acreditive în lei', 'activ'),
('5414', 'Acreditive în valută', 'activ'),
('542', 'Avansuri de trezorerie', 'activ'),
('581', 'Viramente interne', 'bifunctional'),
('591', 'Ajustări pentru pierderea de valoare a acțiunilor deținute la entitățile afiliate', 'pasiv'),
('595', 'Ajustări pentru pierderea de valoare a obligațiunilor emise și răscumpărate', 'pasiv'),
('596', 'Ajustări pentru pierderea de valoare a obligațiunilor', 'pasiv'),
('598', 'Ajustări pentru pierderea de valoare a altor investiții pe termen scurt', 'pasiv'),
('601', 'Cheltuieli cu materiile prime', 'cheltuiala'),
('6021', 'Cheltuieli cu materialele auxiliare', 'cheltuiala'),
('6022', 'Cheltuieli privind combustibilii', 'cheltuiala'),
('6023', 'Cheltuieli privind materialele pentru ambalat', 'cheltuiala'),
('6024', 'Cheltuieli privind piesele de schimb', 'cheltuiala'),
('6025', 'Cheltuieli privind semințele și materialele de plantat', 'cheltuiala'),
('6026', 'Cheltuieli privind furajele', 'cheltuiala'),
('6028', 'Cheltuieli privind alte materiale consumabile', 'cheltuiala'),
('603', 'Cheltuieli privind materialele de natura obiectelor de inventar', 'cheltuiala'),
('604', 'Cheltuieli privind materialele nestocate', 'cheltuiala'),
('6051', 'Cheltuieli privind consumul de energie', 'cheltuiala'),
('6052', 'Cheltuieli privind consumul de apă', 'cheltuiala'),
('6053', 'Cheltuieli privind consumul de gaze naturale', 'cheltuiala'),
('6058', 'Cheltuieli cu alte utilități', 'cheltuiala'),
('606', 'Cheltuieli privind activele biologice de natura stocurilor', 'cheltuiala'),
('607', 'Cheltuieli privind mărfurile', 'cheltuiala'),
('608', 'Cheltuieli privind ambalajele', 'cheltuiala'),
('609', 'Reduceri comerciale primite', 'cheltuiala'),
('611', 'Cheltuieli cu întreținerea și reparațiile', 'cheltuiala'),
('6121', 'Cheltuieli cu redevențele', 'cheltuiala'),
('6122', 'Cheltuieli cu locațiile de gestiune', 'cheltuiala'),
('6123', 'Cheltuieli cu chiriile', 'cheltuiala'),
('613', 'Cheltuieli cu primele de asigurare', 'cheltuiala'),
('614', 'Cheltuieli cu studiile și cercetările', 'cheltuiala'),
('615', 'Cheltuieli cu pregătirea personalului', 'cheltuiala'),
('616', 'Cheltuieli aferente drepturilor de proprietate intelectuală', 'cheltuiala'),
('617', 'Cheltuieli de management', 'cheltuiala'),
('618', 'Cheltuieli de consultanță', 'cheltuiala'),
('621', 'Cheltuieli cu colaboratorii', 'cheltuiala'),
('622', 'Cheltuieli privind comisioanele și onorariile', 'cheltuiala'),
('6231', 'Cheltuieli de protocol', 'cheltuiala'),
('6232', 'Cheltuieli de reclamă și publicitate', 'cheltuiala'),
('624', 'Cheltuieli cu transportul de bunuri și personal', 'cheltuiala'),
('625', 'Cheltuieli cu deplasări, detașări și transferări', 'cheltuiala'),
('626', 'Cheltuieli poștale și taxe de telecomunicații', 'cheltuiala'),
('627', 'Cheltuieli cu serviciile bancare și asimilate', 'cheltuiala'),
('628', 'Alte cheltuieli cu serviciile executate de terți', 'cheltuiala'),
('635', 'Cheltuieli cu alte impozite, taxe și vărsăminte asimilate', 'cheltuiala'),
('6351', 'Cheltuieli cu impozitul suplimentar pentru sectoarele de activitate specifice', 'cheltuiala'),
('641', 'Cheltuieli cu salariile personalului', 'cheltuiala'),
('6421', 'Cheltuieli cu avantajele în natură acordate salariaților', 'cheltuiala'),
('6422', 'Cheltuieli cu tichetele acordate salariaților', 'cheltuiala'),
('643', 'Cheltuieli cu remunerarea în instrumente de capitaluri proprii', 'cheltuiala'),
('644', 'Cheltuieli cu primele reprezentând participarea personalului la profit', 'cheltuiala'),
('6451', 'Cheltuieli privind contribuția unității la asigurările sociale', 'cheltuiala'),
('6452', 'Cheltuieli privind contribuția unității pentru ajutorul de șomaj', 'cheltuiala'),
('6453', 'Cheltuieli privind contribuția angajatorului pentru asigurările sociale de sănătate', 'cheltuiala'),
('6455', 'Cheltuieli privind contribuția unității la asigurările de viață', 'cheltuiala'),
('6456', 'Cheltuieli privind contribuția unității la fondurile de pensii facultative', 'cheltuiala'),
('6457', 'Cheltuieli privind contribuția unității la primele de asigurare voluntară de sănătate', 'cheltuiala'),
('6458', 'Alte cheltuieli privind asigurările și protecția socială', 'cheltuiala'),
('646', 'Cheltuieli privind contribuția asiguratorie pentru muncă', 'cheltuiala'),
('6461', 'Cheltuieli privind contribuția asiguratorie pentru muncă corespunzătoare salariaților', 'cheltuiala'),
('6462', 'Cheltuieli privind contribuția asiguratorie pentru muncă corespunzătoare altor persoane', 'cheltuiala'),
('6511', 'Cheltuieli ocazionate de constituirea fiduciei', 'cheltuiala'),
('6512', 'Cheltuieli din derularea operațiunilor de fiducie', 'cheltuiala'),
('6513', 'Cheltuieli din lichidarea operațiunilor de fiducie', 'cheltuiala'),
('652', 'Cheltuieli cu protecția mediului înconjurător', 'cheltuiala'),
('654', 'Pierderi din creanțe și debitori diverși', 'cheltuiala'),
('655', 'Cheltuieli din reevaluarea imobilizărilor corporale', 'cheltuiala'),
('6581', 'Despăgubiri, amenzi și penalități', 'cheltuiala'),
('6582', 'Donații acordate', 'cheltuiala'),
('6583', 'Cheltuieli privind activele cedate și alte operațiuni de capital', 'cheltuiala'),
('6584', 'Cheltuieli cu sumele sau bunurile acordate ca sponsorizări', 'cheltuiala'),
('6586', 'Cheltuieli reprezentând transferuri și contribuții datorate în baza unor acte normative speciale', 'cheltuiala'),
('6587', 'Cheltuieli privind calamitățile și alte evenimente similare', 'cheltuiala'),
('6588', 'Alte cheltuieli de exploatare', 'cheltuiala'),
('663', 'Pierderi din creanțe legate de participații', 'cheltuiala'),
('6641', 'Cheltuieli privind imobilizările financiare cedate', 'cheltuiala'),
('6642', 'Pierderi din investițiile pe termen scurt cedate', 'cheltuiala'),
('6651', 'Diferențe nefavorabile de curs valutar legate de elementele monetare exprimate în valută', 'cheltuiala'),
('6652', 'Diferențe nefavorabile de curs valutar din evaluarea elementelor monetare care fac parte din investiția netă', 'cheltuiala'),
('666', 'Cheltuieli privind dobânzile', 'cheltuiala'),
('667', 'Cheltuieli privind sconturile acordate', 'cheltuiala'),
('668', 'Alte cheltuieli financiare', 'cheltuiala'),
('6811', 'Cheltuieli de exploatare privind amortizarea imobilizărilor', 'cheltuiala'),
('6812', 'Cheltuieli de exploatare privind provizioanele', 'cheltuiala'),
('6813', 'Cheltuieli de exploatare privind ajustările pentru deprecierea imobilizărilor', 'cheltuiala'),
('6814', 'Cheltuieli de exploatare privind ajustările pentru deprecierea activelor circulante', 'cheltuiala'),
('6817', 'Cheltuieli de exploatare privind ajustările pentru deprecierea fondului comercial', 'cheltuiala'),
('6818', 'Cheltuieli de exploatare privind ajustările pentru deprecierea creanțelor avansuri furnizori', 'cheltuiala'),
('6861', 'Cheltuieli privind actualizarea provizioanelor', 'cheltuiala'),
('6863', 'Cheltuieli financiare privind ajustările pentru pierderea de valoare a imobilizărilor financiare', 'cheltuiala'),
('6864', 'Cheltuieli financiare privind ajustările pentru pierderea de valoare a activelor circulante', 'cheltuiala'),
('6865', 'Cheltuieli financiare privind amortizarea diferențelor aferente titlurilor de stat', 'cheltuiala'),
('6868', 'Cheltuieli financiare privind amortizarea primelor de rambursare a obligațiunilor', 'cheltuiala'),
('691', 'Cheltuieli cu impozitul pe profit', 'cheltuiala'),
('694', 'Cheltuieli cu impozitul pe profit la nivelul impozitului minim pe cifra de afaceri, grup fiscal', 'cheltuiala'),
('695', 'Cheltuieli cu impozitul specific unor activități', 'cheltuiala'),
('697', 'Cheltuieli cu impozitul pe profit la nivelul impozitului minim pe cifra de afaceri', 'cheltuiala'),
('698', 'Cheltuieli cu impozitul pe venit și cu alte impozite', 'cheltuiala'),
('7015', 'Venituri din vânzarea produselor finite', 'venit'),
('7017', 'Venituri din vânzarea produselor agricole', 'venit'),
('7018', 'Venituri din vânzarea activelor biologice de natura stocurilor', 'venit'),
('702', 'Venituri din vânzarea semifabricatelor', 'venit'),
('703', 'Venituri din vânzarea produselor reziduale', 'venit'),
('704', 'Venituri din servicii prestate', 'venit'),
('705', 'Venituri din studii și cercetări', 'venit'),
('706', 'Venituri din redevențe, locații de gestiune și chirii', 'venit'),
('707', 'Venituri din vânzarea mărfurilor', 'venit'),
('708', 'Venituri din activități diverse', 'venit'),
('709', 'Reduceri comerciale acordate', 'venit'),
('711', 'Venituri aferente costurilor stocurilor de produse', 'venit'),
('712', 'Venituri aferente costurilor serviciilor în curs de execuție', 'venit'),
('721', 'Venituri din producția de imobilizări necorporale', 'venit'),
('722', 'Venituri din producția de imobilizări corporale', 'venit'),
('725', 'Venituri din producția de investiții imobiliare', 'venit'),
('7411', 'Venituri din subvenții de exploatare aferente cifrei de afaceri', 'venit'),
('7412', 'Venituri din subvenții de exploatare pentru materii prime și materiale', 'venit'),
('7413', 'Venituri din subvenții de exploatare pentru alte cheltuieli externe', 'venit'),
('7414', 'Venituri din subvenții de exploatare pentru plata personalului', 'venit'),
('7415', 'Venituri din subvenții de exploatare pentru asigurări și protecție socială', 'venit'),
('7416', 'Venituri din subvenții de exploatare pentru alte cheltuieli de exploatare', 'venit'),
('7417', 'Venituri din subvenții de exploatare în caz de calamități și alte evenimente similare', 'venit'),
('7418', 'Venituri din subvenții de exploatare pentru dobânda datorată', 'venit'),
('7419', 'Venituri din subvenții de exploatare aferente altor venituri', 'venit'),
('7511', 'Venituri ocazionate de constituirea fiduciei', 'venit'),
('7512', 'Venituri din derularea operațiunilor de fiducie', 'venit'),
('7513', 'Venituri din lichidarea operațiunilor de fiducie', 'venit'),
('754', 'Venituri din creanțe reactivate și debitori diverși', 'venit'),
('755', 'Venituri din reevaluarea imobilizărilor corporale', 'venit'),
('7581', 'Venituri din despăgubiri, amenzi și penalități', 'venit'),
('7582', 'Venituri din donații primite', 'venit'),
('7583', 'Venituri din vânzarea activelor și alte operațiuni de capital', 'venit'),
('7584', 'Venituri din subvenții pentru investiții', 'venit'),
('7586', 'Venituri reprezentând transferuri cuvenite în baza unor acte normative speciale', 'venit'),
('7588', 'Alte venituri din exploatare', 'venit'),
('7611', 'Venituri din acțiuni deținute la entitățile afiliate', 'venit'),
('7612', 'Venituri din acțiuni deținute la entități asociate', 'venit'),
('7613', 'Venituri din acțiuni deținute la entități controlate în comun', 'venit'),
('7615', 'Venituri din alte imobilizări financiare', 'venit'),
('762', 'Venituri din investiții financiare pe termen scurt', 'venit'),
('7641', 'Venituri din imobilizări financiare cedate', 'venit'),
('7642', 'Câștiguri din investiții pe termen scurt cedate', 'venit'),
('7651', 'Diferențe favorabile de curs valutar legate de elementele monetare exprimate în valută', 'venit'),
('7652', 'Diferențe favorabile de curs valutar din evaluarea elementelor monetare care fac parte din investiția netă', 'venit'),
('766', 'Venituri din dobânzi', 'venit'),
('767', 'Venituri din sconturi obținute', 'venit'),
('768', 'Alte venituri financiare', 'venit'),
('7812', 'Venituri din provizioane', 'venit'),
('7813', 'Venituri din ajustări pentru deprecierea imobilizărilor', 'venit'),
('7814', 'Venituri din ajustări pentru deprecierea activelor circulante', 'venit'),
('7815', 'Venituri din fondul comercial negativ', 'venit'),
('7818', 'Venituri din ajustări pentru deprecierea creanțelor reprezentând avansuri acordate furnizorilor', 'venit'),
('7863', 'Venituri financiare din ajustări pentru pierderea de valoare a imobilizărilor financiare', 'venit'),
('7864', 'Venituri financiare din ajustări pentru pierderea de valoare a activelor circulante', 'venit'),
('7865', 'Venituri financiare din amortizarea diferențelor aferente titlurilor de stat', 'venit'),
('794', 'Venituri din impozitul pe profit la nivelul impozitului minim, grup fiscal', 'venit'),
('8011', 'Giruri și garanții acordate', 'special'),
('8018', 'Alte angajamente acordate', 'special'),
('8021', 'Giruri și garanții primite', 'special'),
('8028', 'Alte angajamente primite', 'special'),
('8031', 'Imobilizări corporale primite cu chirie sau în baza altor contracte similare', 'special'),
('8032', 'Valori materiale primite spre prelucrare sau reparare', 'special'),
('8033', 'Valori materiale primite în păstrare sau custodie', 'special'),
('8034', 'Debitori scoși din activ, urmăriți în continuare', 'special'),
('8035', 'Stocuri de natura obiectelor de inventar date în folosință', 'special'),
('8036', 'Redevențe, locații de gestiune, chirii și alte datorii asimilate', 'special'),
('8037', 'Efecte scontate neajunse la scadență', 'special'),
('8038', 'Bunuri primite în administrare, concesiune, cu chirie și alte bunuri similare', 'special'),
('8039', 'Alte valori în afara bilanțului', 'special'),
('804', 'Certificate verzi', 'special'),
('8051', 'Dobânzi de plătit aferente leasing-ului', 'special'),
('8052', 'Dobânzi de încasat aferente leasing-ului', 'special'),
('806', 'Certificate de emisii de gaze cu efect de seră', 'special'),
('807', 'Active contingente', 'special'),
('808', 'Datorii contingente', 'special'),
('809', 'Creanțe preluate prin cesionare', 'special'),
('891', 'Bilanț de deschidere', 'special'),
('892', 'Bilanț de închidere', 'special'),
('901', 'Decontări interne privind cheltuielile', 'gestiune'),
('902', 'Decontări interne privind producția obținută', 'gestiune'),
('903', 'Decontări interne privind diferențele de preț', 'gestiune'),
('921', 'Cheltuielile activității de bază', 'gestiune'),
('922', 'Cheltuielile activităților auxiliare', 'gestiune'),
('923', 'Cheltuieli indirecte de producție', 'gestiune'),
('924', 'Cheltuieli generale de administrație', 'gestiune'),
('925', 'Cheltuieli de desfacere', 'gestiune'),
('931', 'Costul producției obținute', 'gestiune'),
('933', 'Costul producției în curs de execuție', 'gestiune');
